import { Payee, Payroll, UnionReportRow } from "./types";

export const companySummary = {
  header: {
    entityName: "Acme Productions",
    productionName: "Spring Festival",
    EIN: "12-3456789",
    firstPayrollDate: "2024-01-05",
  },
  totalWages: {
    employees: 125000,
    loanOuts: 30000,
    vendors: 15000,
  },
  employeeFees: {
    fica: 8000,
    medicare: 2000,
    futa: 500,
    suta: 300,
    nycMCTMT: 400,
  },
  unionBenefits: {
    unionA: 2500,
    unionB: 1500,
  },
  miscellaneous: {
    kitBoxFee: 200,
    reimbursement: 300,
    perDiem: 150,
    wellness: 100,
  },
  handlingFees: {
    greenroomFees: 100,
    postage: 50,
  },
};

export const payeesReports: Payee[] = [
  {
    id: 1,
    name: "John Doe",
    ssn: "123-45-6789",
    workDates: "2024-01-05 - 2024-05-01",
    type: "Employee",
    union: "Union A",
    jobTitle: "Technician",
    department: "Engineering",
    workState: "NY",
    residentialState: "NY",
    wages: 35000,
    reimbursements: 500,
    allowances: 1000,
    greenroomFee: 50,
    deductions: {
      federalTax: 4000,
      fica: 2000,
      socialSecurity: 1800,
      medicare: 500,
      nysTax: 1500,
      nycTax: 1200,
      nysPFL: 300,
      nysSDI: 150,
      k401: 1000,
      dues: 200,
      agentManager: 0,
    },
    employerFringe: {
      fica: 2000,
      socialSecurity: 1800,
      medicare: 500,
      futa: 300,
      nySUTA: 150,
      nycMCTMT: 100,
      health: 2000,
      pension: 1500,
      k401Annuity: 1200,
    },
    gender: "Male",
    ageGroup: "26-35",
    unemployment: false,
  },
  {
    id: 2,
    name: "Jane Smith",
    ssn: "987-65-4321",
    workDates: "2024-01-10 - 2024-05-15",
    type: "Contractor",
    union: "Union B",
    jobTitle: "Designer",
    department: "Creative",
    workState: "CA",
    residentialState: "CA",
    wages: 25000,
    reimbursements: 300,
    allowances: 800,
    greenroomFee: 30,
    deductions: {
      federalTax: 2000,
      fica: 1500,
      socialSecurity: 1200,
      medicare: 400,
      nysTax: 0, // Not applicable for CA resident
      nycTax: 0, // Not applicable for CA resident
      nysPFL: 0, // Not applicable for CA resident
      nysSDI: 0, // Not applicable for CA resident
      k401: 500,
      dues: 100,
      agentManager: 200,
    },
    employerFringe: {
      fica: 1500,
      socialSecurity: 1200,
      medicare: 400,
      futa: 200,
      nySUTA: 0, // Not applicable for CA resident
      nycMCTMT: 0, // Not applicable for CA resident
      health: 1500,
      pension: 1000,
      k401Annuity: 800,
    },
    gender: "Female",
    ageGroup: "26-35",
    unemployment: false,
  },
  // Add more example payees as needed
  {
    id: 3,
    name: "Alice Johnson",
    ssn: "111-22-3333",
    workDates: "2024-02-01 - 2024-06-01",
    type: "Employee",
    union: "Union A",
    jobTitle: "Manager",
    department: "Operations",
    workState: "NY",
    residentialState: "NY",
    wages: 45000,
    reimbursements: 700,
    allowances: 1200,
    greenroomFee: 60,
    deductions: {
      federalTax: 5000,
      fica: 2500,
      socialSecurity: 2200,
      medicare: 600,
      nysTax: 2000,
      nycTax: 1600,
      nysPFL: 400,
      nysSDI: 200,
      k401: 1500,
      dues: 300,
      agentManager: 0,
    },
    employerFringe: {
      fica: 2500,
      socialSecurity: 2200,
      medicare: 600,
      futa: 400,
      nySUTA: 200,
      nycMCTMT: 150,
      health: 2500,
      pension: 2000,
      k401Annuity: 1800,
    },
    gender: "Female",
    ageGroup: "36-45",
    unemployment: false,
  },
];

export const unionReports: UnionReportRow[] = [
  {
    weekEnding: "2025-05-24",
    checkDate: "2025-05-28",
    unionsPaid: ["Union A", "Union B"],
    payrollId: "PR-001",
  },
  {
    weekEnding: "2025-05-17",
    checkDate: null,
    unionsPaid: ["Union C"],
    payrollId: "PR-002",
  },
  {
    weekEnding: "2025-05-10",
    checkDate: "2025-05-14",
    unionsPaid: ["Union A"],
    payrollId: "PR-003",
  },
  {
    weekEnding: "2025-05-03",
    checkDate: "2025-05-07",
    unionsPaid: ["Union D", "Union B"],
    payrollId: "PR-004",
  },
];

export const mockPayrolls: Payroll[] = [
  {
    id: "PR001",
    payPeriod: "2024-04-01 to 2024-04-15",
    payDate: "2024-04-18",
    employees: [
      {
        name: "John Doe",
        rate: 50,
        increments: 2,
        reimbursements: 100,
        allowances: 50,
        gross: 1200,
        deductions: 200,
      },
      {
        name: "Jane Smith",
        rate: 65,
        increments: 1,
        reimbursements: 80,
        allowances: 90,
        gross: 1400,
        deductions: 250,
      },
      {
        name: "Tom Brown",
        rate: 70,
        increments: 3,
        reimbursements: 110,
        allowances: 75,
        gross: 1300,
        deductions: 220,
      },
    ],
    vendors: [
      {
        name: "XYZ Agency",
        rate: 80,
        increments: 1,
        reimbursements: 150,
        gross: 1000,
      },
      {
        name: "Design Experts",
        rate: 85,
        increments: 2,
        reimbursements: 130,
        gross: 970,
      },
    ],
  },
  {
    id: "PR002",
    payPeriod: "2024-04-16 to 2024-04-30",
    payDate: "2024-05-03",
    employees: [
      {
        name: "Alice Smith",
        rate: 60,
        increments: 1,
        reimbursements: 120,
        allowances: 70,
        gross: 1300,
        deductions: 180,
      },
      {
        name: "Emma Watson",
        rate: 58,
        increments: 2,
        reimbursements: 95,
        allowances: 85,
        gross: 1275,
        deductions: 195,
      },
    ],
    vendors: [
      {
        name: "Tech Supplies Co",
        rate: 75,
        increments: 2,
        reimbursements: 100,
        gross: 1100,
      },
      {
        name: "Content Writers Ltd",
        rate: 90,
        increments: 3,
        reimbursements: 120,
        gross: 1020,
      },
    ],
  },
  {
    id: "PR003",
    payPeriod: "2024-05-01 to 2024-05-15",
    payDate: "2024-05-18",
    employees: [
      {
        name: "Bob Johnson",
        rate: 55,
        increments: 3,
        reimbursements: 90,
        allowances: 60,
        gross: 1250,
        deductions: 220,
      },
      {
        name: "Lara Croft",
        rate: 67,
        increments: 2,
        reimbursements: 100,
        allowances: 95,
        gross: 1390,
        deductions: 240,
      },
    ],
    vendors: [
      {
        name: "Creative Agency",
        rate: 85,
        increments: 1,
        reimbursements: 130,
        gross: 980,
      },
      {
        name: "Video Creators Inc",
        rate: 95,
        increments: 1,
        reimbursements: 160,
        gross: 1080,
      },
      {
        name: "Brand Studio",
        rate: 77,
        increments: 2,
        reimbursements: 140,
        gross: 990,
      },
    ],
  },
  {
    id: "PR004",
    payPeriod: "2024-05-16 to 2024-05-31",
    payDate: "2024-06-03",
    employees: [
      {
        name: "Charlie Brown",
        rate: 58,
        increments: 2,
        reimbursements: 110,
        allowances: 80,
        gross: 1280,
        deductions: 210,
      },
      {
        name: "Nina Ray",
        rate: 62,
        increments: 2,
        reimbursements: 105,
        allowances: 95,
        gross: 1360,
        deductions: 215,
      },
      {
        name: "Leo Grant",
        rate: 63,
        increments: 1,
        reimbursements: 100,
        allowances: 85,
        gross: 1300,
        deductions: 205,
      },
    ],
    vendors: [
      {
        name: "Design Experts",
        rate: 70,
        increments: 1,
        reimbursements: 90,
        gross: 950,
      },
      {
        name: "Marketing Pros",
        rate: 85,
        increments: 2,
        reimbursements: 115,
        gross: 970,
      },
    ],
  },
  {
    id: "PR005",
    payPeriod: "2024-06-01 to 2024-06-15",
    payDate: "2024-06-18",
    employees: [
      {
        name: "David Lee",
        rate: 62,
        increments: 2,
        reimbursements: 95,
        allowances: 100,
        gross: 1350,
        deductions: 190,
      },
      {
        name: "Sara Khan",
        rate: 66,
        increments: 3,
        reimbursements: 115,
        allowances: 110,
        gross: 1450,
        deductions: 230,
      },
      {
        name: "Victor Paul",
        rate: 64,
        increments: 1,
        reimbursements: 105,
        allowances: 90,
        gross: 1320,
        deductions: 200,
      },
    ],
    vendors: [
      {
        name: "Content Writers Ltd",
        rate: 90,
        increments: 3,
        reimbursements: 120,
        gross: 1020,
      },
      {
        name: "Print House",
        rate: 76,
        increments: 2,
        reimbursements: 125,
        gross: 1010,
      },
    ],
  },
  {
    id: "PR006",
    payPeriod: "2024-06-16 to 2024-06-30",
    payDate: "2024-07-03",
    employees: [
      {
        name: "Ella Wilson",
        rate: 57,
        increments: 1,
        reimbursements: 85,
        allowances: 60,
        gross: 1230,
        deductions: 170,
      },
      {
        name: "Brian Adams",
        rate: 59,
        increments: 2,
        reimbursements: 90,
        allowances: 70,
        gross: 1250,
        deductions: 185,
      },
    ],
    vendors: [
      {
        name: "HR Consultants",
        rate: 88,
        increments: 2,
        reimbursements: 140,
        gross: 1015,
      },
      {
        name: "Finance Gurus",
        rate: 78,
        increments: 2,
        reimbursements: 135,
        gross: 990,
      },
      {
        name: "Legal Support Co",
        rate: 82,
        increments: 1,
        reimbursements: 125,
        gross: 1010,
      },
    ],
  },
  {
    id: "PR007",
    payPeriod: "2024-07-01 to 2024-07-15",
    payDate: "2024-07-18",
    employees: [
      {
        name: "Fiona Green",
        rate: 65,
        increments: 3,
        reimbursements: 130,
        allowances: 90,
        gross: 1400,
        deductions: 250,
      },
      {
        name: "Noah Smith",
        rate: 68,
        increments: 2,
        reimbursements: 125,
        allowances: 100,
        gross: 1420,
        deductions: 245,
      },
      {
        name: "Linda Paul",
        rate: 66,
        increments: 1,
        reimbursements: 115,
        allowances: 80,
        gross: 1355,
        deductions: 215,
      },
      {
        name: "Ray Kim",
        rate: 60,
        increments: 1,
        reimbursements: 100,
        allowances: 95,
        gross: 1295,
        deductions: 200,
      },
    ],
    vendors: [
      {
        name: "Video Creators Inc",
        rate: 95,
        increments: 1,
        reimbursements: 160,
        gross: 1080,
      },
      {
        name: "Legal Support Co",
        rate: 82,
        increments: 1,
        reimbursements: 125,
        gross: 1010,
      },
    ],
  },
  {
    id: "PR008",
    payPeriod: "2024-07-16 to 2024-07-31",
    payDate: "2024-08-03",
    employees: [
      {
        name: "George Martin",
        rate: 60,
        increments: 2,
        reimbursements: 100,
        allowances: 75,
        gross: 1325,
        deductions: 230,
      },
      {
        name: "Olivia White",
        rate: 61,
        increments: 2,
        reimbursements: 90,
        allowances: 70,
        gross: 1265,
        deductions: 210,
      },
    ],
    vendors: [
      {
        name: "Marketing Pros",
        rate: 85,
        increments: 2,
        reimbursements: 115,
        gross: 970,
      },
      {
        name: "Creative Agency",
        rate: 85,
        increments: 1,
        reimbursements: 130,
        gross: 980,
      },
    ],
  },
  {
    id: "PR009",
    payPeriod: "2024-08-01 to 2024-08-15",
    payDate: "2024-08-18",
    employees: [
      {
        name: "Hannah Lee",
        rate: 59,
        increments: 1,
        reimbursements: 105,
        allowances: 65,
        gross: 1260,
        deductions: 200,
      },
      {
        name: "Mason Clark",
        rate: 63,
        increments: 2,
        reimbursements: 100,
        allowances: 85,
        gross: 1330,
        deductions: 210,
      },
    ],
    vendors: [
      {
        name: "Finance Gurus",
        rate: 78,
        increments: 2,
        reimbursements: 135,
        gross: 990,
      },
      {
        name: "Design Experts",
        rate: 70,
        increments: 1,
        reimbursements: 90,
        gross: 950,
      },
    ],
  },
  {
    id: "PR010",
    payPeriod: "2024-08-16 to 2024-08-31",
    payDate: "2024-09-03",
    employees: [
      {
        name: "Ian Clark",
        rate: 61,
        increments: 2,
        reimbursements: 115,
        allowances: 85,
        gross: 1340,
        deductions: 210,
      },
      {
        name: "Lily Adams",
        rate: 62,
        increments: 2,
        reimbursements: 110,
        allowances: 90,
        gross: 1325,
        deductions: 195,
      },
      {
        name: "Kevin Turner",
        rate: 64,
        increments: 1,
        reimbursements: 105,
        allowances: 100,
        gross: 1360,
        deductions: 220,
      },
    ],
    vendors: [
      {
        name: "Legal Support Co",
        rate: 82,
        increments: 1,
        reimbursements: 125,
        gross: 1010,
      },
      {
        name: "XYZ Agency",
        rate: 80,
        increments: 1,
        reimbursements: 150,
        gross: 1000,
      },
    ],
  },
];
